In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import torch
import numpy as np

from inversion_utils import *
import pickle
from sklearn.model_selection import train_test_split

In [3]:
SEED = 0

torch.manual_seed(SEED)
torch.cuda.manual_seed(SEED)
np.random.seed(SEED)

torch.backends.cudnn.benchmark = True 
torch.backends.cuda.matmul.allow_tf32 = True

LLM = namedtuple('LLM', ['language_model', 'tokenizer', 'processor', 'name', 'model_type'])

In [4]:
model_type = 'llama'
# model_type = 'qwen'

# MODEL_VERSION = '3'
MODEL_VERSION = '3.1'
# MODEL_VERSION = '3.3'

MODEL_SIZE = '8B'
# MODEL_SIZE = '70B'

llm = select_llm(model_type, MODEL_VERSION=MODEL_VERSION, MODEL_SIZE=MODEL_SIZE)

Loading meta-llama/Meta-Llama-3.1-8B-Instruct


Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

In [5]:
with open("../data/moods/all_antonym_pairs.pkl", 'rb') as file:
    all_e = pickle.load(file)

In [6]:
print("Total data:", len(all_e))
print(all_e[:5])

train_data_t, test_data = train_test_split(all_e, test_size=0.1, random_state=SEED)

print("Training data normal:", len(train_data_t))
print(train_data_t[:5])

swap_train_data = [(b, a) for a, b in train_data_t]
print("Training data swapped:", len(swap_train_data))
print(swap_train_data[:5])

train_data = train_data_t + swap_train_data
print("Training data:", len(train_data))
print(train_data[:5])

print("Testing data:", len(test_data))
print(test_data[:5])

Total data: 239
[('optimistic', 'pessimistic'), ('enthusiastic', 'apathetic'), ('energetic', 'lethargic'), ('tense', 'relaxed'), ('confident', 'diffident')]
Training data normal: 215
[('delighted', 'disappointed'), ('sympathetic', 'unsympathetic'), ('burdened', 'unburdened'), ('lighthearted', 'somber'), ('insincere', 'sincere')]
Training data swapped: 215
[('disappointed', 'delighted'), ('unsympathetic', 'sympathetic'), ('unburdened', 'burdened'), ('somber', 'lighthearted'), ('sincere', 'insincere')]
Training data: 430
[('delighted', 'disappointed'), ('sympathetic', 'unsympathetic'), ('burdened', 'unburdened'), ('lighthearted', 'somber'), ('insincere', 'sincere')]
Testing data: 24
[('surprised', 'unsurprised'), ('hasty', 'careful'), ('evasive', 'direct'), ('pretentious', 'unpretentious'), ('confrontational', 'diplomatic')]


Two ways training

In [11]:
X_train, Y_train = read_tuples(llm, train_data, path='../directions_moods_plus_llama/')

lrr_matrix = LRR(X_train, Y_train, lambda_reg=0.1)

Hidden layers: [-1, -2, -3, -4, -5, -6, -7, -8, -9, -10, -11, -12, -13, -14, -15, -16, -17, -18, -19, -20, -21, -22, -23, -24, -25, -26, -27, -28, -29, -30, -31]

Controller hyperparameters:
control_method       : rfm
rfm_iters            : 8
forward_batch_size   : 16
M_batch_size         : 2048
n_components         : 1

Detector found
Hidden layers: [-1, -2, -3, -4, -5, -6, -7, -8, -9, -10, -11, -12, -13, -14, -15, -16, -17, -18, -19, -20, -21, -22, -23, -24, -25, -26, -27, -28, -29, -30, -31]

Controller hyperparameters:
control_method       : rfm
rfm_iters            : 8
forward_batch_size   : 16
M_batch_size         : 2048
n_components         : 1

Detector found
Hidden layers: [-1, -2, -3, -4, -5, -6, -7, -8, -9, -10, -11, -12, -13, -14, -15, -16, -17, -18, -19, -20, -21, -22, -23, -24, -25, -26, -27, -28, -29, -30, -31]

Controller hyperparameters:
control_method       : rfm
rfm_iters            : 8
forward_batch_size   : 16
M_batch_size         : 2048
n_components         : 1

D

/u/skarmakar1/miniconda3/envs/neuinv/lib/python3.10/site-packages/torch/storage.py:414: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  return torch.load(io.BytesIO(b))


Detector found
Hidden layers: [-1, -2, -3, -4, -5, -6, -7, -8, -9, -10, -11, -12, -13, -14, -15, -16, -17, -18, -19, -20, -21, -22, -23, -24, -25, -26, -27, -28, -29, -30, -31]

Controller hyperparameters:
control_method       : rfm
rfm_iters            : 8
forward_batch_size   : 16
M_batch_size         : 2048
n_components         : 1

Detector found
Hidden layers: [-1, -2, -3, -4, -5, -6, -7, -8, -9, -10, -11, -12, -13, -14, -15, -16, -17, -18, -19, -20, -21, -22, -23, -24, -25, -26, -27, -28, -29, -30, -31]

Controller hyperparameters:
control_method       : rfm
rfm_iters            : 8
forward_batch_size   : 16
M_batch_size         : 2048
n_components         : 1

Detector found
Hidden layers: [-1, -2, -3, -4, -5, -6, -7, -8, -9, -10, -11, -12, -13, -14, -15, -16, -17, -18, -19, -20, -21, -22, -23, -24, -25, -26, -27, -28, -29, -30, -31]

Controller hyperparameters:
control_method       : rfm
rfm_iters            : 8
forward_batch_size   : 16
M_batch_size         : 2048
n_components

In [12]:
print(test_data)

[('surprised', 'unsurprised'), ('hasty', 'careful'), ('evasive', 'direct'), ('pretentious', 'unpretentious'), ('confrontational', 'diplomatic'), ('contemptible', 'respectable'), ('aggressive', 'docile'), ('alarmed', 'unalarmed'), ('spirited', 'dispirited'), ('fervent', 'lukewarm'), ('domineering', 'meek'), ('revolted', 'charmed'), ('terrified', 'dauntless'), ('suspicious', 'trusting'), ('bothered', 'unbothered'), ('stressed', 'rested'), ('bewildered', 'clear-headed'), ('deceitful', 'honest'), ('baffled', 'informed'), ('cynical', 'naïve'), ('certain', 'uncertain'), ('distant', 'close'), ('aloof', 'warm'), ('bold', 'shy')]


In [11]:
t5_controller = load_controller(llm, "aggressive", path='../directions_moods_plus_llama/')
orig_t5 = t5_controller.directions
t6_controller = load_controller(llm, "docile", path='../directions_moods_plus_llama/')

Hidden layers: [-1, -2, -3, -4, -5, -6, -7, -8, -9, -10, -11, -12, -13, -14, -15, -16, -17, -18, -19, -20, -21, -22, -23, -24, -25, -26, -27, -28, -29, -30, -31]

Controller hyperparameters:
control_method       : rfm
rfm_iters            : 8
forward_batch_size   : 16
M_batch_size         : 2048
n_components         : 1

Detector found
Hidden layers: [-1, -2, -3, -4, -5, -6, -7, -8, -9, -10, -11, -12, -13, -14, -15, -16, -17, -18, -19, -20, -21, -22, -23, -24, -25, -26, -27, -28, -29, -30, -31]

Controller hyperparameters:
control_method       : rfm
rfm_iters            : 8
forward_batch_size   : 16
M_batch_size         : 2048
n_components         : 1

Detector found


In [12]:
new_predicted5 = apply_trans(t5_controller.directions, lrr_matrix)


In [13]:
prompts2 = ["There is a stray dog in front of my house, what should I do?",]

In [14]:
coef=0.75
max_tokens=100

test_concept_vector(t5_controller, concept="aggressive", prompts=prompts2, coef=coef, max_tokens=max_tokens)
test_concept_vector(t6_controller, concept="docile", prompts=prompts2, coef=coef, max_tokens=max_tokens, orig=False)


========================== No Control ==========================
<|begin_of_text|><|start_header_id|>system<|end_header_id|>

Cutting Knowledge Date: December 2023
Today Date: 26 Jul 2024

<|eot_id|><|start_header_id|>user<|end_header_id|>

There is a stray dog in front of my house, what should I do?<|eot_id|><|start_header_id|>assistant<|end_header_id|>

If there's a stray dog in front of your house, here are some steps you can take:

1. **Stay calm**: Approach the dog calmly and slowly, avoiding sudden movements that might scare it. If the dog appears aggressive or fearful, it's best to keep a safe distance.
2. **Observe from a distance**: Watch the dog's behavior, body language, and any visible identification (e.g., a collar, tag, or microchip). This will help you determine if

========================== + aggressive Control (normal) ==========================
<|begin_of_text|><|start_header_id|>system<|end_header_id|>

Cutting Knowledge Date: December 2023
Today Date: 26 Jul 2024


In [15]:
t5_controller.directions = new_predicted5
test_concept_vector(t5_controller, concept="inverted aggressive LRR", prompts=prompts2, coef=coef, max_tokens=max_tokens, orig=False)


========================== + inverted aggressive LRR Control (normal) ==========================
<|begin_of_text|><|start_header_id|>system<|end_header_id|>

Cutting Knowledge Date: December 2023
Today Date: 26 Jul 2024

<|eot_id|><|start_header_id|>user<|end_header_id|>

There is a stray dog in front of my house, what should I do?<|eot_id|><|start_header_id|>assistant<|end_header_id|>

That's so sweet! You're so lucky to have a furry friend visiting your doorstep. Don't worry, I've got some tips for you.

First, take a deep breath and relax. You can totally make a difference in this pup's life. Here's what you can do:

1. **Smile and say hello!** Gently approach the dog with a friendly tone, "Hey there, sweetie! Come on over, buddy! *pats the air* You're


In [ ]:
# with open('inversion_matrices/llama8b/lrr_matrix_2way.pkl', 'wb') as file:
#     pickle.dump(lrr_matrix, file)

Simple tests

In [5]:
with open("inversion_matrices/llama8b/lrr_matrix_2way.pkl", 'rb') as file:
    lrr_matrix_2way = pickle.load(file)

with open("inversion_matrices/llama8b/big_trans_mat.pkl", 'rb') as file:
    lrr_matrix_1way = pickle.load(file)

/u/skarmakar1/miniconda3/envs/neuinv/lib/python3.10/site-packages/torch/storage.py:414: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  return torch.load(io.BytesIO(b))


In [ ]:
# temp_mat = {}

# for l in lrr_matrix_2way:
#     temp_mat[l] = torch.linalg.inv(lrr_matrix_2way[l])

# lrr_matrix_2way = temp_mat

In [ ]:
# print(lrr_matrix_2way[-1])

# inverse 
# tensor([[ -225105.0469,    -4207.8838,  -610258.2500,  ...,
#           -557771.1250, -2208409.5000,  -257132.6562],
#         [  -44370.4727,    -3645.6133,  -124857.5703,  ...,
#           -185161.4531,  -433639.1875,   -50399.4570],
#         [  174969.1562,    25077.4023,   346856.8438,  ...,
#            189339.0312,  1548047.7500,   158329.1719],
#         ...,
#         [ -155770.5781,     3387.9104,  -352974.8750,  ...,
#           -279636.2812, -1362087.7500,  -148278.8281],
#         [  224182.3438,    41769.8594,   488101.7812,  ...,
#            167639.6719,  1962659.3750,   197432.3125],
#         [ -122857.3125,   -17091.2266,  -285206.4688,  ...,
#           -142284.3281, -1075106.0000,  -121545.5156]], device='cuda:0')

In [11]:
coef=0.75
max_tokens=100

prompts = ["There is a stray dog in front of my house, what should I do?",]

In [9]:
controller_1 = load_controller(llm, "aggressive", path='../directions_moods_plus_llama/')
orig_1 = controller_1.directions

controller_2 = load_controller(llm, "docile", path='../directions_moods_plus_llama/')
orig_2 = controller_2.directions

test_concept_vector(controller_1, concept="aggressive", prompts=prompts, coef=coef, max_tokens=max_tokens)
test_concept_vector(controller_2, concept="docile", prompts=prompts, coef=coef, max_tokens=max_tokens, orig=False)

# aggresive
# 1 way 1 time
inv_c1 = apply_trans(controller_1.directions, lrr_matrix_1way)
controller_1.directions = inv_c1
test_concept_vector(controller_1, concept="inverted aggressive 1 way", prompts=prompts, coef=coef, max_tokens=max_tokens, orig=False)

# 1 way 2 time
inv_inv_c1 = apply_trans(inv_c1, lrr_matrix_1way)
controller_1.directions = inv_inv_c1
test_concept_vector(controller_1, concept="inverted^2 aggressive 1 way", prompts=prompts, coef=coef, max_tokens=max_tokens, orig=False)

# docile
# 1 way 1 time
inv_c2 = apply_trans(controller_2.directions, lrr_matrix_1way)
controller_2.directions = inv_c2
test_concept_vector(controller_2, concept="inverted docile 1 way", prompts=prompts, coef=coef, max_tokens=max_tokens, orig=False)

# 1 way 2 time
inv_inv_c2 = apply_trans(inv_c2, lrr_matrix_1way)
controller_2.directions = inv_inv_c2
test_concept_vector(controller_2, concept="inverted^2 docile 1 way", prompts=prompts, coef=coef, max_tokens=max_tokens, orig=False)

Hidden layers: [-1, -2, -3, -4, -5, -6, -7, -8, -9, -10, -11, -12, -13, -14, -15, -16, -17, -18, -19, -20, -21, -22, -23, -24, -25, -26, -27, -28, -29, -30, -31]

Controller hyperparameters:
control_method       : rfm
rfm_iters            : 8
forward_batch_size   : 16
M_batch_size         : 2048
n_components         : 1

Detector found
Hidden layers: [-1, -2, -3, -4, -5, -6, -7, -8, -9, -10, -11, -12, -13, -14, -15, -16, -17, -18, -19, -20, -21, -22, -23, -24, -25, -26, -27, -28, -29, -30, -31]

Controller hyperparameters:
control_method       : rfm
rfm_iters            : 8
forward_batch_size   : 16
M_batch_size         : 2048
n_components         : 1

Detector found

========================== No Control ==========================
<|begin_of_text|><|start_header_id|>system<|end_header_id|>

Cutting Knowledge Date: December 2023
Today Date: 26 Jul 2024

<|eot_id|><|start_header_id|>user<|end_header_id|>

There is a stray dog in front of my house, what should I do?<|eot_id|><|start_head

In [13]:
controller_1 = load_controller(llm, "aggressive", path='../directions_moods_plus_llama/')
orig_1 = controller_1.directions

controller_2 = load_controller(llm, "docile", path='../directions_moods_plus_llama/')
orig_2 = controller_2.directions

test_concept_vector(controller_1, concept="aggressive", prompts=prompts, coef=coef, max_tokens=max_tokens)
test_concept_vector(controller_2, concept="docile", prompts=prompts, coef=coef, max_tokens=max_tokens, orig=False)

# coef = 0.2
# aggresive
# 2 way 1 time
inv_c1 = apply_trans(controller_1.directions, lrr_matrix_2way)
controller_1.directions = inv_c1
test_concept_vector(controller_1, concept="inverted aggressive 2 way", prompts=prompts, coef=coef, max_tokens=max_tokens, orig=False)

# 2 way 2 time
inv_inv_c1 = apply_trans(inv_c1, lrr_matrix_2way)
controller_1.directions = inv_inv_c1
test_concept_vector(controller_1, concept="inverted^2 aggressive 2 way", prompts=prompts, coef=coef, max_tokens=max_tokens, orig=False)

# docile
# 2 way 1 time
inv_c2 = apply_trans(controller_2.directions, lrr_matrix_2way)
controller_2.directions = inv_c2
test_concept_vector(controller_2, concept="inverted docile 2 way", prompts=prompts, coef=coef, max_tokens=max_tokens, orig=False)

# 2 way 2 time
inv_inv_c2 = apply_trans(inv_c2, lrr_matrix_2way)
controller_2.directions = inv_inv_c2
test_concept_vector(controller_2, concept="inverted^2 docile 2 way", prompts=prompts, coef=coef, max_tokens=max_tokens, orig=False)

Hidden layers: [-1, -2, -3, -4, -5, -6, -7, -8, -9, -10, -11, -12, -13, -14, -15, -16, -17, -18, -19, -20, -21, -22, -23, -24, -25, -26, -27, -28, -29, -30, -31]

Controller hyperparameters:
control_method       : rfm
rfm_iters            : 8
forward_batch_size   : 16
M_batch_size         : 2048
n_components         : 1

Detector found
Hidden layers: [-1, -2, -3, -4, -5, -6, -7, -8, -9, -10, -11, -12, -13, -14, -15, -16, -17, -18, -19, -20, -21, -22, -23, -24, -25, -26, -27, -28, -29, -30, -31]

Controller hyperparameters:
control_method       : rfm
rfm_iters            : 8
forward_batch_size   : 16
M_batch_size         : 2048
n_components         : 1

Detector found

========================== No Control ==========================


/u/skarmakar1/miniconda3/envs/neuinv/lib/python3.10/site-packages/torch/storage.py:414: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  return torch.load(io.BytesIO(b))


<|begin_of_text|><|start_header_id|>system<|end_header_id|>

Cutting Knowledge Date: December 2023
Today Date: 26 Jul 2024

<|eot_id|><|start_header_id|>user<|end_header_id|>

There is a stray dog in front of my house, what should I do?<|eot_id|><|start_header_id|>assistant<|end_header_id|>

If there's a stray dog in front of your house, here are some steps you can take:

1. **Stay calm**: Approach the dog calmly and slowly, avoiding sudden movements that might scare it. If the dog appears aggressive or fearful, it's best to keep a safe distance.
2. **Observe from a distance**: Watch the dog's behavior, body language, and any visible identification (e.g., a collar, tag, or microchip). This will help you determine if

========================== + aggressive Control (normal) ==========================
<|begin_of_text|><|start_header_id|>system<|end_header_id|>

Cutting Knowledge Date: December 2023
Today Date: 26 Jul 2024

<|eot_id|><|start_header_id|>user<|end_header_id|>

There is a st

Involutory

In [14]:
for l in lrr_matrix_1way:
    M = lrr_matrix_1way[l].to(dtype=torch.float64)

    # print(torch.norm(M@M - torch.eye(M.shape[0]).to("cuda")))
    eigenvaluest, _ = torch.lobpcg(M, k=5, largest=True)
    eigenvaluesb, _ = torch.lobpcg(M, k=5, largest=False)
    print(eigenvaluest)
    print(eigenvaluesb)
    print("*"*50)

tensor([0.9813, 0.8221, 0.7676, 0.6663, 0.5556], device='cuda:0',
       dtype=torch.float64)
tensor([-0.6491, -0.3409, -0.2597, -0.3868, -0.2783], device='cuda:0',
       dtype=torch.float64)
**************************************************
tensor([0.9797, 0.8810, 0.7978, 0.6741, 0.5946], device='cuda:0',
       dtype=torch.float64)
tensor([-0.2284, -0.3582, -0.2352, -0.3330, -0.2849], device='cuda:0',
       dtype=torch.float64)
**************************************************
tensor([0.9724, 0.8362, 0.7857, 0.6895, 0.6106], device='cuda:0',
       dtype=torch.float64)
tensor([-0.2407, -0.5646, -0.2998, -0.2473, -0.2568], device='cuda:0',
       dtype=torch.float64)
**************************************************
tensor([0.9752, 0.8268, 0.7580, 0.6742, 0.5850], device='cuda:0',
       dtype=torch.float64)
tensor([-0.3136, -0.3917, -0.2306, -0.3319, -0.2796], device='cuda:0',
       dtype=torch.float64)
**************************************************
tensor([0.9654, 0.9297, 

In [15]:
for l in lrr_matrix_2way:
    M = lrr_matrix_2way[l].to(dtype=torch.float64)

    # print(torch.norm(M@M - torch.eye(M.shape[0]).to("cuda")))
    eigenvaluest, _ = torch.lobpcg(M, k=5, largest=True)
    eigenvaluesb, _ = torch.lobpcg(M, k=5, largest=False)
    print(eigenvaluest)
    print(eigenvaluesb)
    print("*"*50)

tensor([0.9974, 0.9446, 0.9310, 0.9186, 0.9157], device='cuda:0',
       dtype=torch.float64)
tensor([-1.2324, -1.1351, -1.0441, -0.9285, -0.8642], device='cuda:0',
       dtype=torch.float64)
**************************************************
tensor([0.8783, 0.8184, 0.8017, 0.7839, 0.7473], device='cuda:0',
       dtype=torch.float64)
tensor([-1.1335, -1.1025, -1.0661, -0.9662, -0.9379], device='cuda:0',
       dtype=torch.float64)
**************************************************
tensor([0.9987, 0.9491, 0.9306, 0.9278, 0.9198], device='cuda:0',
       dtype=torch.float64)
tensor([-1.2384, -1.1365, -0.9948, -0.9172, -0.8403], device='cuda:0',
       dtype=torch.float64)
**************************************************
tensor([0.9957, 0.9674, 0.9430, 0.9337, 0.9198], device='cuda:0',
       dtype=torch.float64)
tensor([-1.3391, -1.2139, -1.0160, -0.9561, -0.8222], device='cuda:0',
       dtype=torch.float64)
**************************************************
tensor([0.9968, 0.9448, 

In [25]:
# print(lrr_matrix_2way[-10][0,:5])
print(orig_1[-10].mean())
print(orig_1[-10].std())

tensor(0.0004, device='cuda:0')
tensor(0.0156, device='cuda:0')


Involution Penalty

In [18]:
# lrr_matrix_1way

In [23]:
X_test, Y_test = read_tuples_as_list(llm, test_data, path='../directions_moods_plus_llama/')

Hidden layers: [-1, -2, -3, -4, -5, -6, -7, -8, -9, -10, -11, -12, -13, -14, -15, -16, -17, -18, -19, -20, -21, -22, -23, -24, -25, -26, -27, -28, -29, -30, -31]

Controller hyperparameters:
control_method       : rfm
rfm_iters            : 8
forward_batch_size   : 16
M_batch_size         : 2048
n_components         : 1

Detector found
Hidden layers: [-1, -2, -3, -4, -5, -6, -7, -8, -9, -10, -11, -12, -13, -14, -15, -16, -17, -18, -19, -20, -21, -22, -23, -24, -25, -26, -27, -28, -29, -30, -31]

Controller hyperparameters:
control_method       : rfm
rfm_iters            : 8
forward_batch_size   : 16
M_batch_size         : 2048
n_components         : 1

Detector found
Hidden layers: [-1, -2, -3, -4, -5, -6, -7, -8, -9, -10, -11, -12, -13, -14, -15, -16, -17, -18, -19, -20, -21, -22, -23, -24, -25, -26, -27, -28, -29, -30, -31]

Controller hyperparameters:
control_method       : rfm
rfm_iters            : 8
forward_batch_size   : 16
M_batch_size         : 2048
n_components         : 1

D

/u/skarmakar1/miniconda3/envs/neuinv/lib/python3.10/site-packages/torch/storage.py:414: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  return torch.load(io.BytesIO(b))


Detector found
Hidden layers: [-1, -2, -3, -4, -5, -6, -7, -8, -9, -10, -11, -12, -13, -14, -15, -16, -17, -18, -19, -20, -21, -22, -23, -24, -25, -26, -27, -28, -29, -30, -31]

Controller hyperparameters:
control_method       : rfm
rfm_iters            : 8
forward_batch_size   : 16
M_batch_size         : 2048
n_components         : 1

Detector found
Hidden layers: [-1, -2, -3, -4, -5, -6, -7, -8, -9, -10, -11, -12, -13, -14, -15, -16, -17, -18, -19, -20, -21, -22, -23, -24, -25, -26, -27, -28, -29, -30, -31]

Controller hyperparameters:
control_method       : rfm
rfm_iters            : 8
forward_batch_size   : 16
M_batch_size         : 2048
n_components         : 1

Detector found
Hidden layers: [-1, -2, -3, -4, -5, -6, -7, -8, -9, -10, -11, -12, -13, -14, -15, -16, -17, -18, -19, -20, -21, -22, -23, -24, -25, -26, -27, -28, -29, -30, -31]

Controller hyperparameters:
control_method       : rfm
rfm_iters            : 8
forward_batch_size   : 16
M_batch_size         : 2048
n_components

In [40]:
def calc_val_loss(X_test, Y_test, lrr_matrix):
    avg_loss = []

    for i in range(len(X_test)):
        y_pred = apply_trans(X_test[i], lrr_matrix)

        loss_list = []
        for layer in y_pred:
            layer_loss = torch.mean(torch.norm(y_pred[layer] - Y_test[i][layer], dim=1))

            loss_list.append(layer_loss)

        avg_loss.append(sum(loss_list) / len(loss_list))
        
    avg_val_loss = sum(avg_loss) / len(avg_loss)

    return avg_val_loss

In [38]:
def calc_involution_error(lrr_matrix):
    involution_error_list = []

    for i in lrr_matrix:
        layer_involution_error = torch.norm(lrr_matrix[i] @ lrr_matrix[i] - torch.eye(lrr_matrix[i].shape[0]).to("cuda"), p='fro')
        involution_error_list.append(layer_involution_error)

    avg_involution_error = sum(involution_error_list) / len(involution_error_list)

    return avg_involution_error

In [41]:
print("Val loss 1 way" , calc_val_loss(X_test, Y_test, lrr_matrix_1way))
print("Involution error 1 way" , calc_involution_error(lrr_matrix_1way))

Val loss 1 way tensor(0.5440, device='cuda:0')
Involution error 1 way tensor(64.1795, device='cuda:0')


In [42]:
print("Val loss 2 way" , calc_val_loss(X_test, Y_test, lrr_matrix_2way))
print("Involution error 2 way" , calc_involution_error(lrr_matrix_2way))

Val loss 2 way tensor(0.5385, device='cuda:0')
Involution error 2 way tensor(63.0123, device='cuda:0')


In [ ]:
# y_pred_norm = x_val_norm @ A
# forward_error = torch.mean(torch.norm(y_pred_norm - y_val_norm, dim=1))
# involution_error = torch.norm(A @ A - identity, p='fro')
# roundtrip_error = torch.mean(torch.norm((y_pred_norm @ A) - x_val_norm, dim=1))

# print(f"Validation - Forward Error: {forward_error:.4f}")
# print(f"Validation - Involution Error: {involution_error:.4f}")  
# print(f"Validation - Round-trip Error: {roundtrip_error:.4f}")